spring:
  config:
    import: file:env.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      default-schema: public
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.mail.yahoo.com
jwt:
  secret: ${JWT_SECRET}
  expirationMs: 900000